---
- hosts: ntp
  remote_user: ansible
  become: yes

  tasks:
  - name: install NTP
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - ntp
      state: latest

  - name: config NTP
    template:
      src: /ansible/templates/ntp/ntp.conf
      dest: /etc/ntp.conf
    notify:
    - restart NTP

  - name: ensure NTP is runnig
    service:
      name: ntpd
      state: restarted

  handlers:
  - name : restart NTP
    service:
      name: ntpd
      state: started
